---
- hosts: all
  tasks:
    - name: Include the variables
      include_vars: env.vars

- import_playbook: playbooks/test.yml
- import_playbook: playbooks/setup.yml
- import_playbook: playbooks/worker.yml
