---
- hosts: all

  tasks:
    - name: Wait till the joining tokens are created
      local_action:
        module: wait_for
        state: present
        path: '{{ token_file }}'

    - name: Join the Cluster
      shell: '{{ lookup("file", token_file) }} >> {{ node_log_file }}'
      become: yes
      become_method: sudo
      args:
        chdir: '{{ ansible_env.HOME }}'
        creates: '{{ node_log_file }}'
